sonar.projectKey=githubclone_app
sonar.projectName=GitHub Clone Project

# Projenin ana kaynak kod dizinleri
sonar.sources=./backend/src,./frontend/src

# Test ve kütüphane dosyalarını tarama dışı bırak
sonar.exclusions=**/*.spec.ts,**/node_modules/**

# Host URL, Docker Compose'daki servis adını kullanıyoruz
sonar.host.url=http://localhost:9000

# Analiz için giriş token'ı (SonarQube arayüzünden oluşturulacak)
sonar.login=sqp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
